### PR TITLE
Added snapshots support

### PR DESCRIPTION
**Pull request by tomitrescak**
This PR add snapshot support a'la JEST.
To do this, I needed to allow user configure several properties, that are accessible via "TestConfig".

```js
import { TestConfig } from 'fuse-test-runner';
TestConfig.snapshotDir // configures root dir of all snapshots
TestConfig.serializer  // [(obj: any) => string;] configures the serialiser. For backwards compatibility I am using the same serializer as JEST.
```

GOTCHAS:

1. I don't know how to access path to the current test to save snapshots next to tests
2. My approach will not work the moment you will execute your tests in parallel and not in waterfall as I depend on global variable to set the context for currently executed test

### CODE REVIEW

**Comment by tomitrescak** [comment]
I forgot to mention that to update your snapshots you only need to call it like following:

```
UPDATE_SNAPSHOTS=true node fuse test
```

**Comment by tomitrescak** [comment]
Hi, it has become a bit more chunky. I needed to support several features for my browser reporter and snapshot handler, so I added some new parameters to reporter as well. Please review and let me know.

Just so you know, here is the test handler app: https://github.com/tomitrescak/luis-app ... it is not yet ready for primetime.

**Comment by nchanged** [comment]
Good job!
Just to be clear, if you don't want to use Snapshots nothing will change right? I mean i am using this runner in many projects, don't want to have anything broken ;-)

**Comment by tomitrescak** [comment]
@nchanged original functionality was not touched at all .. What was changed:

1. Documentation created
2. Added 'pretty-format' package to generate snapshots
3. Added non-compulsory config that fine tunes snapshots handling
4. Added new Exception related to snapshots
5. Added some more information passed to Reporters
6. Added new snapshot matcher
7. Added the wallaby transform for rnnning your tests in wallaby

So, from my perspective the original functionality should be preserved, but you may want to give it a test run from master on one of your projects. I guess unit tests would be good ;)

**Pull request merged**
